name: run realworld api tests
on:
  workflow_dispatch
jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        uses: gothinkster/realworld-api-action@v1.5
        with:
          url: 'https://api.realworld.io/api'
